version: '3'

services:
  laravel:
    image: erasmojr/laravel:prod
    container_name: laravel
    networks:
      - laranet

  nginx:
    image: erasmojr/nginx:prod
    container_name: nginx
    networks:
      - laranet
    ports:
      - "8080:80"


networks:
  laranet:
    drive: bridge
